import type { StorybookConfig } from '@storybook/nextjs';
import { VanillaExtractPlugin } from '@vanilla-extract/webpack-plugin';
import MiniCssExtractPlugin from 'mini-css-extract-plugin';

import { satoshiFontStyles } from './fonts';

const config: StorybookConfig = {
  stories: ['../docs/**/*.mdx', '../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    '@storybook/addon-a11y',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-links',
    '@storybook/addon-themes',
    '@storybook/addon-viewport',
    '@chromatic-com/storybook',
  ],
  framework: {
    name: '@storybook/nextjs',
    options: { strictMode: true },
  },
  features: {
    experimentalRSC: true,
  },
  core: { disableWhatsNewNotifications: true },
  staticDirs: [
    '../public',
    {
      from: '../src/styles/font-satoshi',
      to: 'styles/font-satoshi',
    },
  ],
  typescript: {
    check: true,
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      // Filter out all HTMLAttributes and DOMAttribute props
      // (inherited from HTML-like elements and showing in the docs (for shadcn components)
      propFilter: (prop, component) => !prop.parent?.name.includes('Attribute'),
      shouldRemoveUndefinedFromOptional: true,
      shouldExtractLiteralValuesFromEnum: true,
      shouldExtractValuesFromUnion: true,
    },
  },

  managerHead: (head) => `
    ${head}
    <!-- TODO: replace with our icon -->
    <!-- <link rel="icon" type="image/png" href="/logo192.png" sizes="192x192" /> -->
    <meta name="robots" content="noindex" />
  `,

  previewHead: (head) => `
    ${head}
    <style>
      ${satoshiFontStyles}

      .sbdocs-content h3 + p {
        margin-top: 0;
      }
    </style>
 `,
  // previewBody: (body) => `
  //   <div class="entire-body-for-preview-frame-incl-mdx-docs">
  //     ${body}
  //   </div>
  // `,

  /**
   * @storybook/addon-styling-webpack doesn't seem to work for @vanilla-extract,
   * so this entire webpack config below is for that, to support it.
   *
   * Taken from Stackblitz example referenced here:
   * @url https://storybook.js.org/recipes/@vanilla-extract/css
   */
  webpackFinal(config, options) {
    config.devtool = 'eval-cheap-source-map';

    // By default, Storybook only adds here node_modules
    // If we also run NestJS on the side (which builds to .next dir), it constantly re-builds
    config.watchOptions = {
      ...config.watchOptions,
      aggregateTimeout: 500,
      ignored: /(node_modules|\.cache|\.dist|\.next|test-e2e)/,
    };

    // Add Vanilla-Extract and MiniCssExtract Plugins
    config.plugins!.push(new VanillaExtractPlugin(), new MiniCssExtractPlugin());

    // Exclude vanilla extract files from regular css processing
    config.module?.rules?.forEach((rule) => {
      if (typeof rule === 'object' && rule?.test instanceof RegExp && rule.test.test('test.css')) {
        rule.exclude = /\.vanilla\.css$/i;
      }
    });

    config.module?.rules?.push({
      test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
      use: [
        MiniCssExtractPlugin.loader,
        {
          loader: require.resolve('css-loader'),
          // Required as image imports should be handled via JS/TS import statements
          options: { url: false },
        },
      ],
    });

    // console.log('STORYBOOK WEBPACK', { config });
    return config;
  },
};

export default config;
