/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: UserDto;
    'esim-cards': EsimCardDto;
    orders: OrderItemDto;
    transactions: TransactionDto;
    'esim-products': EsimProductDto;
    destinations: DestinationDto;
    regions: RegionDto;
    'esim-providers': EsimProviderDto;
    media: MediaDto;
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    'blog-tags': BlogTag;
    'ai-pages': AiPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    transactions: {
      orderItems: 'orders';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'esim-cards': EsimCardsSelect<false> | EsimCardsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'esim-products': EsimProductsSelect<false> | EsimProductsSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    'esim-providers': EsimProvidersSelect<false> | EsimProvidersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-tags': BlogTagsSelect<false> | BlogTagsSelect<true>;
    'ai-pages': AiPagesSelect<false> | AiPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('de' | 'en' | 'es' | 'fr' | 'pl' | 'ru')
    | ('de' | 'en' | 'es' | 'fr' | 'pl' | 'ru')[];
  globals: {
    'esim-products-data': EsimProductsContent;
  };
  globalsSelect: {
    'esim-products-data': EsimProductsDataSelect<false> | EsimProductsDataSelect<true>;
  };
  locale: 'de' | 'en' | 'es' | 'fr' | 'pl' | 'ru';
  user: UserDto & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Private eSIM customers and our PayloadCMS users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface UserDto {
  id: string;
  fullName?: string | null;
  roles: ('admin' | 'editor' | 'support' | 'customer')[];
  lastActiveAt?: string | null;
  stripeCustomerId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "esim-cards".
 */
export interface EsimCardDto {
  id: string;
  /**
   * eSIM card status, in SM-DP+ server.
   */
  statusSmdp: 'ephemeral' | 'created' | 'activated' | 'suspended' | 'disabled' | 'error' | 'unrecognized';
  orderedPackages: {
    orderItem: string | OrderItemDto;
    product?: (string | null) | EsimProductDto;
    productName?: string | null;
    productType?: string | null;
    createdAt?: string | null;
    id?: string | null;
  }[];
  /**
   * eSIM Card history log. Changes in ICCID numbers. It might contain multiple entries if/when the eSIM Card replacement has been ordered.
   */
  esimHistory: {
    iccid: string;
    supplierOrderId: string;
    happenedAt: string;
    installationStatus?: ('new' | 'installed') | null;
    installedAt?: string | null;
    id?: string | null;
  }[];
  setup: EsimCardSetup;
  /**
   * Customer who owns/manages the eSIM in their wallet.
   */
  user: string | UserDto;
  usageTracking: boolean;
  /**
   * Quick call *code to get the current usage.
   */
  usageTrackingCode?: string | null;
  provider: string | EsimProviderDto;
  supplier: 'mm';
  usageLastSyncAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface OrderItemDto {
  id: string;
  product: string | EsimProductDto;
  /**
   * eSIM for which this product has been bought. If empty, the order (for eSIM starter) hasn't been fulfilled yet.
   */
  esimCard?: (string | null) | EsimCardDto;
  usage?: PackageUsageDto;
  status?: OrderItemLiveStatusDto;
  usageLastSyncAt?: string | null;
  title: string;
  transaction: string | TransactionDto;
  transactionPaymentStatus?:
    | (
        | 'requires_payment_method'
        | 'requires_confirmation'
        | 'requires_action'
        | 'requires_capture'
        | 'processing'
        | 'canceled'
        | 'succeeded'
      )
    | null;
  price: number;
  supplierPrice: number;
  profit?: number | null;
  /**
   * Customer who owns/manages the item in their wallet.
   */
  user: string | UserDto;
  fulfillment: OrderFulfillment;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "esim-products".
 */
export interface EsimProductDto {
  id: string;
  name: string;
  productPricing: EsimProductPricing;
  planType: '0' | '1' | '2';
  planKycPolicy: '0' | '1';
  planValidity: number;
  planDataAllowance: number;
  planVoiceAllowance: number;
  planMaxSpeed: '4g' | '5g';
  destinations?: (string | DestinationDto)[] | null;
  regions?: (string | RegionDto)[] | null;
  productAttributes?:
    | {
        name?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  supplier: 'mm';
  supplierProductId: string;
  supplierProductCreationDate: string;
  supplierProductLastUpdate: string;
  supplierImportData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  productType: 'eSIM' | 'eSIMdelayed' | 'TopUp' | 'Replacement';
  provider: string | EsimProviderDto;
  productFamily: string;
  productFamilyTopUpsCount?: number | null;
  usageTracking?: boolean | null;
  /**
   * AI-generated HTML content for product page
   */
  aiGeneratedHtml?: string | null;
  /**
   * Motion and visual settings (JSON)
   */
  aiVisualConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Image generation prompts (JSON)
   */
  aiImagePrompts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EsimProductPricing".
 */
export interface EsimProductPricing {
  listPrice: number;
  supplierPrice: number;
  profit?: number | null;
  pricePerGb?: number | null;
  pricePerMin?: number | null;
  competitorPrices:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * Destination. Usually a country. Can be a city / state within country.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface DestinationDto {
  /**
   * ISO 2-letter country code or ISO-<suffix> for city destinations. All lowercase.
   */
  id: string;
  name: string;
  published?: boolean | null;
  isTopDestination?: boolean | null;
  slug: string;
  currency?: string | null;
  region: string | RegionDto;
  productStats?: {
    allProducts?: number | null;
    eSimProducts?: number | null;
    topUpProducts?: number | null;
    priceFrom?: number | null;
    pricePerGbFrom?: number | null;
  };
  /**
   * Search keywords: alternative names, major city names, states, etc.
   */
  keywords?: string | null;
  /**
   * Coma-separated alternative ISO codes, used to map destinations to destination codes used by eSIM providers.
   */
  altIsoCodes?: string[] | null;
  /**
   * For destinations which aren't countries, set country information here.
   */
  parentDestination?: (string | null) | DestinationDto;
  /**
   * AI-generated HTML content for destination page
   */
  aiGeneratedHtml?: string | null;
  /**
   * Motion and visual settings (JSON)
   */
  aiVisualConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Image generation prompts (JSON)
   */
  aiImagePrompts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface RegionDto {
  id: string;
  name: string;
  productStats?: {
    allProducts?: number | null;
    eSimProducts?: number | null;
    topUpProducts?: number | null;
    priceFrom?: number | null;
    pricePerGbFrom?: number | null;
  };
  slug: string;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "esim-providers".
 */
export interface EsimProviderDto {
  id: string;
  name: string;
  websiteUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Data Plan current usage etc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PackageUsageDto".
 */
export interface PackageUsageDto {
  activationDate?: string | null;
  expirationDate?: string | null;
  mbUsed?: number | null;
  mbAllowance?: number | null;
  mbUsageDelta?: number | null;
  minUsed?: number | null;
  minAllowance?: number | null;
  minUsageDelta?: number | null;
}
/**
 * Plan / Package "live" statuses, based on latest usage data received from Provider.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderItemLiveStatusDto".
 */
export interface OrderItemLiveStatusDto {
  isActivelyUsingAllowance?: boolean | null;
  isPackageExpired?: boolean | null;
  isPackageUsedUp?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface TransactionDto {
  id: string;
  user: string | UserDto;
  total: number;
  orderItems?: {
    docs?: (string | OrderItemDto)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  paymentStatus?:
    | (
        | 'requires_payment_method'
        | 'requires_confirmation'
        | 'requires_action'
        | 'requires_capture'
        | 'processing'
        | 'canceled'
        | 'succeeded'
      )
    | null;
  paymentId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderFulfillment".
 */
export interface OrderFulfillment {
  /**
   * Order State from Supplier.
   */
  status: 'New' | 'Fulfilled' | 'Processing' | 'Cancelled' | 'Expired' | 'Error';
  supplier: 'mm';
  supplierProductId: string;
  supplierOrderId?: string | null;
  fulfilledAt?: string | null;
}
/**
 * eSIM card technical details, related to installation and activation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EsimCardSetup".
 */
export interface EsimCardSetup {
  /**
   * eSIM ICCID, Integrated Circuit Card Identifier, a unique number that identifies the eSIM itself (on SM-DP+ server).
   */
  iccid: string;
  phoneNo?: string | null;
  /**
   * SM-DP+ server address of your carrier's Subscription Manager Data Preparation system (which prepares, stores and deliver eSIM profiles).
   */
  smdpAddress: string;
  activationCode: string;
  confirmationCode?: string | null;
  /**
   * Local Profile Assistant URL. This is the only info needed to prepare/install eSIM and this is what is included in QR code.
   */
  lpa: string;
  /**
   * Access Point Name i.e. Internet gateway, where the Internet traffic is routed.
   */
  apn: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface MediaDto {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Manage blog posts, including creating, updating, and categorizing posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: SeoMetaData;
  /**
   * Required for published posts. Optional for AI-generated drafts.
   */
  featuredImage?: (string | null) | MediaDto;
  markAsTopPost?: boolean | null;
  slug: string;
  /**
   * Brief summary of the post
   */
  excerpt?: string | null;
  /**
   * Auto-set when post is published
   */
  publishedDate?: string | null;
  /**
   * Auto-set from current user if empty
   */
  author?: (string | null) | UserDto;
  tags?: (string | BlogTag)[] | null;
  categories?: (string | BlogCategory)[] | null;
  views?: number | null;
  shares?: number | null;
  metricsTopPostScore?: number | null;
  /**
   * Content cluster for AI CMS routing
   */
  contentCluster?: ('blog' | 'support' | 'about' | 'legal') | null;
  /**
   * AI-generated HTML content for rendering
   */
  aiGeneratedHtml?: string | null;
  /**
   * Motion and visual settings (JSON)
   */
  aiVisualConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Image generation prompts (JSON)
   */
  aiImagePrompts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoMetaData".
 */
export interface SeoMetaData {
  title?: string | null;
  description?: string | null;
  /**
   * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
   */
  image?: (string | null) | MediaDto;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags".
 */
export interface BlogTag {
  id: string;
  tag: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: string;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI-powered page creation and management with BigMind
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-pages".
 */
export interface AiPage {
  id: string;
  title: string;
  /**
   * Unique identifier for this page
   */
  key: string;
  /**
   * e.g., /blog/my-article or /support/faq
   */
  urlPath: string;
  pageType?: ('standard' | 'landing' | 'article' | 'product' | 'destination') | null;
  template?: ('default' | 'pillar-overview' | 'blog-article' | 'faq' | 'comparison' | 'hero-landing') | null;
  status?: ('draft' | 'published' | 'scheduled' | 'archived') | null;
  parentPage?: (string | null) | AiPage;
  contentCluster?: ('blog' | 'support' | 'about' | 'legal' | 'science' | 'products' | 'destinations') | null;
  priority?: number | null;
  /**
   * Brief summary of the page content...
   */
  summary?: string | null;
  /**
   * Main page content
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * AI-generated HTML content
   */
  rawHtmlContent?: string | null;
  seoFocusKeyword?: string | null;
  /**
   * Leave empty to use page title
   */
  seoTitle?: string | null;
  /**
   * Meta description for search engines
   */
  seoDescription?: string | null;
  /**
   * https://example.com/image.jpg
   */
  featuredImageUrl?: string | null;
  /**
   * Detailed prompt for generating hero images...
   */
  aiImagePrompt?: string | null;
  /**
   * Detailed prompt for generating background videos...
   */
  aiVideoPrompt?: string | null;
  /**
   * Additional notes for designers or developers...
   */
  designerNotes?: string | null;
  visualPriority?: ('p1' | 'p2' | 'p3') | null;
  visualCluster?: string | null;
  /**
   * Comma-separated
   */
  vibeKeywords?: string | null;
  /**
   * Comma-separated
   */
  emotionalTone?: string | null;
  /**
   * Comma-separated
   */
  animationIdeas?: string | null;
  motionPreset?:
    | (
        | 'none'
        | 'liquid-crystal-float'
        | 'energetic-pulse'
        | 'magnetic-drift'
        | 'krystal-bloom'
        | 'scalar-slide'
        | 'vortex-reveal'
        | 'parallax-depth'
        | 'ripple-emergence'
        | 'subtle-shimmer'
        | 'layered-parallax'
      )
    | null;
  /**
   * e.g., fadeUp, scaleIn, slideFromLeft
   */
  entranceMotion?: string | null;
  /**
   * e.g., hover.lift, hover.glow, hover.scale
   */
  hoverMotion?: string | null;
  /**
   * e.g., ambient.float, ambient.pulse
   */
  ambientMotion?: string | null;
  heroSectionMotion?: string | null;
  contentSectionsMotion?: string | null;
  cardsBoxesMotion?: string | null;
  /**
   * Lucide icon name for navigation (e.g., Beaker, Flask, Droplet)
   */
  pageIcon?: string | null;
  mediaGallery?:
    | {
        mediaUrl?: string | null;
        mediaType?: ('image' | 'video') | null;
        altText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * AI conversation history for this page
   */
  aiChatHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Most recent prompt sent to BigMind
   */
  aiLastPrompt?: string | null;
  publishedAt?: string | null;
  internalLinks?: (string | AiPage)[] | null;
  externalLinks?:
    | {
        url?: string | null;
        anchorText?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | UserDto;
      } | null)
    | ({
        relationTo: 'esim-cards';
        value: string | EsimCardDto;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | OrderItemDto;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | TransactionDto;
      } | null)
    | ({
        relationTo: 'esim-products';
        value: string | EsimProductDto;
      } | null)
    | ({
        relationTo: 'destinations';
        value: string | DestinationDto;
      } | null)
    | ({
        relationTo: 'regions';
        value: string | RegionDto;
      } | null)
    | ({
        relationTo: 'esim-providers';
        value: string | EsimProviderDto;
      } | null)
    | ({
        relationTo: 'media';
        value: string | MediaDto;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: string | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-tags';
        value: string | BlogTag;
      } | null)
    | ({
        relationTo: 'ai-pages';
        value: string | AiPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | UserDto;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | UserDto;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  roles?: T;
  lastActiveAt?: T;
  stripeCustomerId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "esim-cards_select".
 */
export interface EsimCardsSelect<T extends boolean = true> {
  id?: T;
  statusSmdp?: T;
  orderedPackages?:
    | T
    | {
        orderItem?: T;
        product?: T;
        productName?: T;
        productType?: T;
        createdAt?: T;
        id?: T;
      };
  esimHistory?:
    | T
    | {
        iccid?: T;
        supplierOrderId?: T;
        happenedAt?: T;
        installationStatus?: T;
        installedAt?: T;
        id?: T;
      };
  setup?: T | EsimCardSetupSelect<T>;
  user?: T;
  usageTracking?: T;
  usageTrackingCode?: T;
  provider?: T;
  supplier?: T;
  usageLastSyncAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EsimCardSetup_select".
 */
export interface EsimCardSetupSelect<T extends boolean = true> {
  iccid?: T;
  phoneNo?: T;
  smdpAddress?: T;
  activationCode?: T;
  confirmationCode?: T;
  lpa?: T;
  apn?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  id?: T;
  product?: T;
  esimCard?: T;
  usage?: T | PackageUsageDtoSelect<T>;
  status?: T | OrderItemLiveStatusDtoSelect<T>;
  usageLastSyncAt?: T;
  title?: T;
  transaction?: T;
  transactionPaymentStatus?: T;
  price?: T;
  supplierPrice?: T;
  profit?: T;
  user?: T;
  fulfillment?: T | OrderFulfillmentSelect<T>;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PackageUsageDto_select".
 */
export interface PackageUsageDtoSelect<T extends boolean = true> {
  activationDate?: T;
  expirationDate?: T;
  mbUsed?: T;
  mbAllowance?: T;
  mbUsageDelta?: T;
  minUsed?: T;
  minAllowance?: T;
  minUsageDelta?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderItemLiveStatusDto_select".
 */
export interface OrderItemLiveStatusDtoSelect<T extends boolean = true> {
  isActivelyUsingAllowance?: T;
  isPackageExpired?: T;
  isPackageUsedUp?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderFulfillment_select".
 */
export interface OrderFulfillmentSelect<T extends boolean = true> {
  status?: T;
  supplier?: T;
  supplierProductId?: T;
  supplierOrderId?: T;
  fulfilledAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  id?: T;
  user?: T;
  total?: T;
  orderItems?: T;
  paymentStatus?: T;
  paymentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "esim-products_select".
 */
export interface EsimProductsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  productPricing?: T | EsimProductPricingSelect<T>;
  planType?: T;
  planKycPolicy?: T;
  planValidity?: T;
  planDataAllowance?: T;
  planVoiceAllowance?: T;
  planMaxSpeed?: T;
  destinations?: T;
  regions?: T;
  productAttributes?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  supplier?: T;
  supplierProductId?: T;
  supplierProductCreationDate?: T;
  supplierProductLastUpdate?: T;
  supplierImportData?: T;
  productType?: T;
  provider?: T;
  productFamily?: T;
  productFamilyTopUpsCount?: T;
  usageTracking?: T;
  aiGeneratedHtml?: T;
  aiVisualConfig?: T;
  aiImagePrompts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EsimProductPricing_select".
 */
export interface EsimProductPricingSelect<T extends boolean = true> {
  listPrice?: T;
  supplierPrice?: T;
  profit?: T;
  pricePerGb?: T;
  pricePerMin?: T;
  competitorPrices?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  published?: T;
  isTopDestination?: T;
  slug?: T;
  currency?: T;
  region?: T;
  productStats?:
    | T
    | {
        allProducts?: T;
        eSimProducts?: T;
        topUpProducts?: T;
        priceFrom?: T;
        pricePerGbFrom?: T;
      };
  keywords?: T;
  altIsoCodes?: T;
  parentDestination?: T;
  aiGeneratedHtml?: T;
  aiVisualConfig?: T;
  aiImagePrompts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  productStats?:
    | T
    | {
        allProducts?: T;
        eSimProducts?: T;
        topUpProducts?: T;
        priceFrom?: T;
        pricePerGbFrom?: T;
      };
  slug?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "esim-providers_select".
 */
export interface EsimProvidersSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  websiteUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  meta?: T | SeoMetaDataSelect<T>;
  featuredImage?: T;
  markAsTopPost?: T;
  slug?: T;
  excerpt?: T;
  publishedDate?: T;
  author?: T;
  tags?: T;
  categories?: T;
  views?: T;
  shares?: T;
  metricsTopPostScore?: T;
  contentCluster?: T;
  aiGeneratedHtml?: T;
  aiVisualConfig?: T;
  aiImagePrompts?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeoMetaData_select".
 */
export interface SeoMetaDataSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags_select".
 */
export interface BlogTagsSelect<T extends boolean = true> {
  tag?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-pages_select".
 */
export interface AiPagesSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  urlPath?: T;
  pageType?: T;
  template?: T;
  status?: T;
  parentPage?: T;
  contentCluster?: T;
  priority?: T;
  summary?: T;
  content?: T;
  rawHtmlContent?: T;
  seoFocusKeyword?: T;
  seoTitle?: T;
  seoDescription?: T;
  featuredImageUrl?: T;
  aiImagePrompt?: T;
  aiVideoPrompt?: T;
  designerNotes?: T;
  visualPriority?: T;
  visualCluster?: T;
  vibeKeywords?: T;
  emotionalTone?: T;
  animationIdeas?: T;
  motionPreset?: T;
  entranceMotion?: T;
  hoverMotion?: T;
  ambientMotion?: T;
  heroSectionMotion?: T;
  contentSectionsMotion?: T;
  cardsBoxesMotion?: T;
  pageIcon?: T;
  mediaGallery?:
    | T
    | {
        mediaUrl?: T;
        mediaType?: T;
        altText?: T;
        id?: T;
      };
  aiChatHistory?: T;
  aiLastPrompt?: T;
  publishedAt?: T;
  internalLinks?: T;
  externalLinks?:
    | T
    | {
        url?: T;
        anchorText?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Product-related content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "esim-products-data".
 */
export interface EsimProductsContent {
  id: string;
  dynamicContent?: {
    items?:
      | {
          id?: string | null;
          content?: string | null;
        }[]
      | null;
  };
  aboutText?: {
    items?:
      | {
          content?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "esim-products-data_select".
 */
export interface EsimProductsDataSelect<T extends boolean = true> {
  dynamicContent?:
    | T
    | {
        items?:
          | T
          | {
              id?: T;
              content?: T;
            };
      };
  aboutText?:
    | T
    | {
        items?:
          | T
          | {
              content?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EsimProductBlock".
 */
export interface EsimProductBlock {
  title?: string | null;
  subtitle?: string | null;
  locations?:
    | (
        | {
            relationTo: 'destinations';
            value: string | DestinationDto;
          }
        | {
            relationTo: 'regions';
            value: string | RegionDto;
          }
      )[]
    | null;
  products?: (string | EsimProductDto)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'esim-products';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}