import { Destination, makeDestinationObj } from '@/data/destination';
import { DestinationDto } from '@/payload/app-types';

import {
  mockRegionDtoAmerica,
  mockRegionDtoAsia,
  mockRegionDtoEurope,
  mockRegionDtoLatAm,
  mockRegionDtoMiddleEast,
} from './regions.mock';

export const mockDestinationsDto: DestinationDto[] = [
  {
    id: 'us',
    name: 'United States',
    published: true,
    isTopDestination: true,
    slug: 'united-states',
    currency: 'USD',
    region: mockRegionDtoAmerica,
    keywords: 'Washington, New York, California, Los Angeles, Chicago, Texas, Arizona',
    createdAt: '2024-04-25T10:40:42.571Z',
    updatedAt: '2024-04-25T10:40:42.571Z',
  },
  {
    id: 'gb',
    name: 'United Kingdom',
    published: true,
    isTopDestination: true,
    slug: 'united-kingdom',
    currency: 'GBP',
    region: mockRegionDtoEurope,
    keywords: 'London, Scotland, Wales, Ireland, Birmingham, Manchester, Glasgow, Leeds',
    createdAt: '2024-04-25T10:40:42.571Z',
    updatedAt: '2024-04-25T10:40:42.571Z',
  },
  {
    id: 'ae',
    name: 'United Arab Emirates',
    published: true,
    isTopDestination: false,
    slug: 'united-arab-emirates',
    currency: 'AED',
    region: mockRegionDtoMiddleEast,
    keywords: 'Abu Dhabi',
    createdAt: '2024-04-25T10:40:42.571Z',
    updatedAt: '2024-04-25T10:40:42.571Z',
  },
  {
    id: 'th',
    name: 'Thailand',
    published: true,
    isTopDestination: true,
    slug: 'thailand',
    currency: 'THB',
    region: mockRegionDtoAsia,
    keywords: 'Bangkok',
    createdAt: '2024-04-25T10:40:42.570Z',
    updatedAt: '2024-04-25T10:40:42.570Z',
  },
  {
    id: 'es',
    name: 'Spain',
    published: true,
    isTopDestination: true,
    slug: 'spain',
    currency: 'EUR',
    region: mockRegionDtoEurope,
    keywords: 'Madrid',
    createdAt: '2024-04-25T10:40:42.570Z',
    updatedAt: '2024-04-25T10:40:42.570Z',
  },
  {
    id: 'pl',
    name: 'Poland',
    published: true,
    isTopDestination: false,
    slug: 'poland',
    currency: 'PLN',
    region: mockRegionDtoEurope,
    keywords: 'Warszawa',
    createdAt: '2024-04-25T10:40:42.570Z',
    updatedAt: '2024-04-25T10:40:42.570Z',
  },
  {
    id: 'ph',
    name: 'Philippines',
    published: true,
    isTopDestination: false,
    slug: 'philippines',
    currency: 'PHP',
    region: mockRegionDtoAsia,
    keywords: 'Manila',
    createdAt: '2024-04-25T10:40:42.570Z',
    updatedAt: '2024-04-25T10:40:42.570Z',
  },
  {
    id: 'gb-nir',
    name: 'Northern Ireland',
    published: true,
    isTopDestination: false,
    slug: 'northern-ireland',
    currency: 'GBP',
    region: mockRegionDtoEurope,
    keywords: 'Belfast',
    parentDestination: 'gb',
    createdAt: '2024-04-25T10:40:42.570Z',
    updatedAt: '2024-04-25T10:40:42.570Z',
  },
  {
    id: 'id',
    name: 'Indonesia',
    published: true,
    isTopDestination: false,
    slug: 'indonesia',
    currency: 'IDR',
    region: mockRegionDtoAsia,
    keywords: 'Jakarta, Bali, Yogyakarta, Komodo. Lombok, Sumatra, Java',
    createdAt: '2024-04-25T10:40:42.569Z',
    updatedAt: '2024-04-25T10:40:42.569Z',
  },
  {
    id: 'ht',
    name: 'Haiti',
    published: true,
    isTopDestination: false,
    slug: 'haiti',
    currency: 'HTG',
    region: mockRegionDtoLatAm,
    keywords: 'Port-au-Prince',
    altIsoCodes: ['us-hi'],
    createdAt: '2024-04-25T10:40:42.569Z',
    updatedAt: '2024-04-25T10:40:42.569Z',
  },
  {
    id: 'br',
    name: 'Brazil',
    published: true,
    isTopDestination: true,
    slug: 'brazil',
    currency: 'BRL',
    region: mockRegionDtoLatAm,
    keywords: 'Brasília',
    createdAt: '2024-04-25T10:40:42.568Z',
    updatedAt: '2024-04-25T10:40:42.568Z',
  },
];

export const mockDestinationUSA = makeDestinationObj(mockDestinationsDto[0]);
export const mockDestinationUK = makeDestinationObj(mockDestinationsDto[1]);
export const mockDestinationUAE = makeDestinationObj(mockDestinationsDto[2]);
export const mockDestinationTh = makeDestinationObj(mockDestinationsDto[3]);
export const mockDestinationSe = makeDestinationObj(mockDestinationsDto[4]);
export const mockDestinationPl = makeDestinationObj(mockDestinationsDto[5]);
export const mockDestinationHk = makeDestinationObj({
  id: 'hk',
  slug: 'hong-kong',
  name: 'Hong Kong',
  region: mockRegionDtoAsia,
  updatedAt: '',
  createdAt: '',
});
export const mockDestinationTw = makeDestinationObj({
  id: 'tw',
  slug: 'taiwan',
  name: 'Taiwan',
  region: mockRegionDtoAsia,
  updatedAt: '',
  createdAt: '',
});

export const mockDestinations: Destination[] = [
  mockDestinationUSA,
  mockDestinationUK,
  mockDestinationUAE,
  mockDestinationTh,
  mockDestinationSe,
  mockDestinationPl,
  mockDestinationHk,
  mockDestinationTw,
];
