/**
 * Fields to send from the front-end forms, when sending ReCaptcha data
 */
export interface ReCaptchaFormData {
  /**
   * ReCaptcha performed action
   */
  reCaptchaAction: RecaptchaAction;

  /**
   * ReCaptcha token generated by `executeRecaptcha()` on the client side
   */
  reCaptchaToken: string;
}

/**
 * Recommended ReCaptcha actions
 * @see https://cloud.google.com/recaptcha-enterprise/docs/actions-website
 */
export enum RecaptchaAction {
  /**
   * Sign up on the website.
   */
  Signup = 'signup',
  /**
   * Log in to the website.
   */
  Login = 'login',
  /**
   * Request to reset the password.
   */
  PasswordReset = 'password_reset',
  /**
   * Add items to the cart.
   */
  CartAdd = 'cart_add',
  /**
   * View the contents of the cart.
   */
  CartView = 'cart_view',
  /**
   * Check out from the website.
   */
  Checkout = 'checkout',
  /**
   * Add or update payment information (e.g. card details or address).
   */
  Payment = 'payment_add',
  /**
   * Confirmation that a transaction was processed.
   */
  Transaction = 'transaction_confirmed',
}
